config/routes.rb
Priut::Application.routes.draw do

  devise_for :users
  root :to => 'home#index'
  get 'adddog', :to => 'dogs#new'
  post 'dogs', :to => 'dogs#add'

  match 'user/:id', :to =>'user#show', :as => :user
  match 'dog/:id', :to =>'dogs#show', :as => :dog

end

app/models/dog.rb
class Dog

  include Mongoid::Document
  include Mongoid::Timestamps 
  field :name
  field :breed
  field :sex
  field :slug
  key :name, :slug

  mount_uploader :image, ImageUploader

#  :inclusion => { :in => [1,2,3] }
  attr_accessible :name, :breed, :sex,:image
  referenced_in :user, :inverse_of => :user
#    embedded_in :user , :inverse_of => :dogs

  before_validation :set_slug

  def set_slug
    self.slug = rand(36**8).to_s(36) if self.slug.nil?
  end

end

app/models/user.rb
class User
  include Mongoid::Document

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  field :name

  key :name

  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation

    references_many :dogs, :inverse_of => :dogs
   # embeds_many :dogs, :class_name => "Dog"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_filter :authenticate_user! , :except =>[:show]
  def new
    @dog = Dog.new
    @name=current_user.name
  end

  def show
    @dog = Dog.first(:conditions => { :id => params[:id] })
    raise 'error' if @dog.nil?
  end

  def add
    @dog = Dog.new(params[:dog])
    @dog.user=current_user
    if @dog.save
      flash[:notice] = "Successfully created..."

#      render 'new'
    else
      flash[:error] = "failed"
#      render 'new'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @dogs=Dog.all()

    
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index

  end
  
  def show
    @user= User.first(:conditions => { :name => params[:id] })
    raise 'error' if @user.nil?
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options! 
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
  
  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/dogs/add.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "add.html" %>

app/views/dogs/new.html.erb
<h1>Добавить собаку</h1>
<%=@name%>
<%= form_for @dog, :html => {:multipart => true} do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :breed %><br />
    <%= f.text_field :breed %>
  </div>
    <div class="field">
    <%= f.label :sex %><br />
    <%= f.text_field :sex %>
  </div>
<div class="field">
   <label>My Avatar</label>
        <%= f.file_field :image %>
        <%= f.hidden_field :image_cache %>

</div>
  <div class="actions">
    <%= f.submit "добавить" %>
  </div>
<% end %>

app/views/dogs/show.html.erb
<%= @dog.name %><br />
 <%= image_tag(@dog.image.url) if @dog.image? %> <br />
<%= link_to  @dog.user.name, user_path(@dog.user.id)  %><br />

app/views/home/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'Logout', destroy_user_session_path %>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>
<%= link_to 'добавить собаку', adddog_path   %>
<br />
<%@dogs.each do |dog|%>
<%= dog.name%><br />
<% if !dog.user.nil? %>
<%= link_to dog.user.id, user_path(dog.user.id)  %><br />


<% end %>
<span>---------------</span><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/user/show.html.erb
<%=@user.name%><br />
<%@user.dogs.each do |dog|%>
<%if !dog.slug.nil? %>
<%= link_to  dog.name, dog_path(dog.id)  %><br />
<% end %>
 <%= image_tag(dog.image.url(:thumb)) if dog.image? %>
<br />
<% end %>